import type { Medicine } from "./types";

export const initialMedicines: Medicine[] = [
  {
    id: "1",
    name: "Paracetamol 500mg",
    description: "Utilizat pentru a trata durerea și a reduce febra. Este de obicei folosit pentru a calma durerile ușoare până la moderate, cum ar fi durerile de cap, durerile de dinți sau entorsele, și pentru a reduce febra cauzată de boli precum răceala și gripa.",
    medicineType: "Pastilă",
    quantity: 50,
    purchaseDate: "2023-10-01",
    expiryDate: "2025-09-30",
    imageUrl: "https://picsum.photos/seed/paracetamol/400/300",
    imageHint: "white pills",
  },
  {
    id: "2",
    name: "Ibuprofen 200mg",
    description: "Un medicament antiinflamator nesteroidian (AINS) utilizat pentru ameliorarea durerii, ajutând la scăderea febrei și reducerea inflamației.",
    medicineType: "Pastilă",
    quantity: 24,
    purchaseDate: "2024-01-15",
    expiryDate: "2024-08-15",
    imageUrl: "https://picsum.photos/seed/ibuprofen/400/300",
    imageHint: "orange pills",
  },
  {
    id: "3",
    name: "Sirop de tuse",
    description: "Un medicament lichid utilizat pentru a calma tusea cauzată de răceala comună, bronșită și alte afecțiuni respiratorii.",
    medicineType: "Sirop",
    quantity: 1,
    purchaseDate: "2023-11-20",
    expiryDate: "2024-05-30",
    imageUrl: "https://picsum.photos/seed/coughsyrup/400/300",
    imageHint: "syrup bottle",
  },
  {
    id: "4",
    name: "Vitamina C 1000mg",
    description: "O vitamină și un antioxidant care joacă un rol important în susținerea unui sistem imunitar sănătos și menținerea sănătății pielii, cartilajelor și oaselor.",
    medicineType: "Pastilă",
    quantity: 100,
    purchaseDate: "2024-03-01",
    expiryDate: "2026-03-01",
  },
  {
    id: "5",
    name: "Cremă antiseptică",
    description: "O cremă topică utilizată pentru a preveni infecția în tăieturi minore, zgârieturi și arsuri, prin uciderea sau oprirea creșterii microorganismelor.",
    medicineType: "Cremă",
    quantity: 1,
    purchaseDate: "2023-05-10",
    expiryDate: "2025-05-10",
    imageUrl: "https://picsum.photos/seed/antiseptic/400/300",
    imageHint: "cream tube",
  },
  {
    id: "6",
    name: "Antialergic",
    description: "Medicament utilizat pentru a trata simptomele alergiilor, cum ar fi strănutul, nasul care curge, ochii care mănâncă sau lăcrimează și urticaria.",
    medicineType: "Pastilă",
    quantity: 30,
    purchaseDate: "2024-04-12",
    expiryDate: "2025-10-12",
  },
];
